spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rules_db
    username: rules_creator
    password: rule_12345
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.yaml